# Generated by Django 5.0.6

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "phone",
                    models.CharField(
                        help_text="Used for SOS dispatch / TEST SMS.", max_length=20
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Father', 'Mother', 'Neighbour' — free text.",
                        max_length=50,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary guardian contact (e.g. #1 - PRIMARY GUARDIAN). Only one per owner.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The parent account this contact belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "name"],
            },
        ),
    ]
