# Generated by Django 5.0.6 on 2026-05-08 09:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Geofence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Centre point latitude",
                        max_digits=9,
                    ),
                ),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "radius_m",
                    models.IntegerField(default=100, help_text="Radius in metres"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Each device has its own set of geofences.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofences",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
