# Generated by Django 5.0.6 on 2026-05-08 09:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("PANIC", "Panic Button"),
                            ("GEOFENCE", "Geofence Breach"),
                            ("MOTION", "Suspicious Motion"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Location at time of alert",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("sms_sent", models.BooleanField(default=False)),
                ("sms_sent_at", models.DateTimeField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="alerts_aler_device__102fbb_idx",
                    ),
                    models.Index(
                        fields=["resolved"], name="alerts_aler_resolve_7ed9e5_idx"
                    ),
                ],
            },
        ),
    ]
