# Generated by Django 5.0.6 on 2026-05-08 09:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="6 decimal places ≈ 0.1 m accuracy",
                        max_digits=9,
                    ),
                ),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, help_text="GPS accuracy in metres", null=True
                    ),
                ),
                (
                    "speed",
                    models.FloatField(blank=True, help_text="m/s from GPS", null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_readings",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="locations_l_device__e1affc_idx",
                    )
                ],
            },
        ),
    ]
